//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XJFAdmin
    {

        /// <summary>
		/// 用戶id
        /// </summary>		
		private string _xjfadminid;
        public string XJFAdminID
        {
            get { return _xjfadminid; }
            set { _xjfadminid = value; }
        }
        /// <summary>
        /// 角色ID
        /// </summary>		
        private string _xjfroleid;
        public string XJFRoleID
        {
            get { return _xjfroleid; }
            set { _xjfroleid = value; }
        }
        /// <summary>
        /// 登陸名
        /// </summary>		
        private string _xjfadminlgoinname;
        public string XJFAdminLgoinName
        {
            get { return _xjfadminlgoinname; }
            set { _xjfadminlgoinname = value; }
        }
        /// <summary>
        /// 手機號碼
        /// </summary>		
        private string _xjfadminphone;
        public string XJFAdminPhone
        {
            get { return _xjfadminphone; }
            set { _xjfadminphone = value; }
        }
        /// <summary>
        /// 用戶郵箱
        /// </summary>		
        private string _xjfadminemall;
        public string XJFAdminEmall
        {
            get { return _xjfadminemall; }
            set { _xjfadminemall = value; }
        }
        /// <summary>
        /// 用戶登陸密碼
        /// </summary>		
        private string _xjfadminpassword;
        public string XJFAdminPassWord
        {
            get { return _xjfadminpassword; }
            set { _xjfadminpassword = value; }
        }
        /// <summary>
        /// 管理员名称
        /// </summary>		
        private string _xjfadminname;
        public string XJFAdminName
        {
            get { return _xjfadminname; }
            set { _xjfadminname = value; }
        }
        /// <summary>
        /// 头像
        /// </summary>		
        private string _xjfadminheader;
        public string XJFAdminHeader
        {
            get { return _xjfadminheader; }
            set { _xjfadminheader = value; }
        }
        /// <summary>
		/// 用戶性別 ：0、女  1、男 默認為1
        /// </summary>		
		private bool _xjfadminsex;
        public bool XJFAdminSex
        {
            get { return _xjfadminsex; }
            set { _xjfadminsex = value; }
        }
        /// <summary>
        /// 微信ID
        /// </summary>		
        private string _xjfadminwechatid;
        public string XJFAdminWechatID
        {
            get { return _xjfadminwechatid; }
            set { _xjfadminwechatid = value; }
        }
        /// <summary>
        /// qqID
        /// </summary>		
        private string _xjfadmintencentid;
        public string XJFAdminTencentID
        {
            get { return _xjfadmintencentid; }
            set { _xjfadmintencentid = value; }
        }
        /// <summary>
        /// 支付宝ID
        /// </summary>		
        private string _xjfadminalipayid;
        public string XJFAdminAliPayID
        {
            get { return _xjfadminalipayid; }
            set { _xjfadminalipayid = value; }
        }
        /// <summary>
        /// 創建者編號
        /// </summary>		
        private string _xjfcreateid;
        public string XJFCreateID
        {
            get { return _xjfcreateid; }
            set { _xjfcreateid = value; }
        }
        /// <summary>
		/// 創建時間
        /// </summary>		
		private Nullable<System.DateTime> _xjfcreatetime;
        public Nullable<System.DateTime> XJFCreateTime
        {
            get { return _xjfcreatetime; }
            set { _xjfcreatetime = value; }
        }

        /// <summary>
        /// 修改人ID
        /// </summary>		
        private string _xjfupdateid;
        public string XJFUpdateID
        {
            get { return _xjfupdateid; }
            set { _xjfupdateid = value; }
        }
        /// <summary>
        /// 修改时间
        /// </summary>		
        private Nullable<System.DateTime> _xjfupdatetime;
        public Nullable<System.DateTime> XJFUpdateTime
        {
            get { return _xjfupdatetime; }
            set { _xjfupdatetime = value; }
        }
        /// <summary>
		/// 删除者编号
        /// </summary>		
		private string _xjfdelectid;
        public string XJFDelectID
        {
            get { return _xjfdelectid; }
            set { _xjfdelectid = value; }
        }
        /// <summary>
        /// 删除时间
        /// </summary>		
        private Nullable<System.DateTime> _xjfdelecttime;
        public Nullable<System.DateTime> XJFDelectTime
        {
            get { return _xjfdelecttime; }
            set { _xjfdelecttime = value; }
        }
        /// <summary>
        /// 排序序号
        /// </summary>		
        private int _xjfstort;
        public int XJFStort
        {
            get { return _xjfstort; }
            set { _xjfstort = value; }
        }
        /// <summary>
        /// 状态 1、启用 0、禁用
        /// </summary>		
        private bool _xjfstatu;
        public bool XJFStatu
        {
            get { return _xjfstatu; }
            set { _xjfstatu = value; }
        }

        public virtual XJFRole XJFRole { get; set; }
    }

    /// <summary>
    /// 登录对象
    /// </summary>
    public class LoginModel
    {
        private string loginname;
        private string password;
        private string yzm;

        public string Loginname { get => loginname; set => loginname = value; }
        public string Password { get => password; set => password = value; }
        public string Yzm { get => yzm; set => yzm = value; }
    }
}
