//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XJFAuthority
    {
        public int XJFAuthorityID { get; set; }
        public string XJFRoleID { get; set; }
        public string XJFMenuID { get; set; }
    
        public virtual XJFMenu XJFMenu { get; set; }
        public virtual XJFRole XJFRole { get; set; }
    }
}
