//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XJFMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XJFMenu()
        {
            this.XJFAuthority = new HashSet<XJFAuthority>();
        }
    
        public string XJFMenuID { get; set; }
        public string XJFMenuName { get; set; }
        public string XJFMenuWebURL { get; set; }
        public string XJFMenuClass { get; set; }
        public string XJFMenuImg { get; set; }
        public string XJFMenuParentID { get; set; }
        public string XJFCreateID { get; set; }
        public Nullable<System.DateTime> XJFCreateTime { get; set; }
        public string XJFUpdateID { get; set; }
        public Nullable<System.DateTime> XJFUpdateTime { get; set; }
        public string XJFDelectID { get; set; }
        public Nullable<System.DateTime> XJFDelectTime { get; set; }
        public int XJFStort { get; set; }
        public Nullable<bool> XJFStatu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XJFAuthority> XJFAuthority { get; set; }
    }
}
